"""Settings section builders."""

from ui.views.settings.sections import (
    about,
    advanced,
    ai_models,
    appearance_themes,
    backup_restore,
    contact_feedback,
    desktop_companion,
    diagnostics,
    general,
    help,
    integrations,
    knowledge,
    license_section,
    memory,
    notifications,
    privacy_data,
    voice_audio,
)

__all__ = [
    "about",
    "advanced",
    "ai_models",
    "appearance_themes",
    "backup_restore",
    "contact_feedback",
    "desktop_companion",
    "diagnostics",
    "general",
    "help",
    "integrations",
    "knowledge",
    "license_section",
    "memory",
    "notifications",
    "privacy_data",
    "voice_audio",
]
