#!/usr/bin/env python3
"""Stage 4 (milestone M2) — precompute openWakeWord features for negatives + validation.

THE CORE FOSS-LICENSING FIX. Instead of downloading the notebook's non-commercial
ACAV100M / validation feature files, this regenerates equivalent ``(N, 16, 96)``
feature arrays from commercially-licensed audio (LibriSpeech / MUSAN) by running it
through openWakeWord's Apache-2.0 melspectrogram + embedding models.

Outputs (paths come from the config's ``data`` block):
  - data.negative_features        bulk negative training features
  - data.fp_validation_features   held-out false-positive validation set

Each output gets a ``<asset>.license.json`` provenance sidecar so verify_licenses.py
stays green.

Usage:
    python scripts/precompute_features.py --config configs/hey_qube.yaml --set all
    python scripts/precompute_features.py --config configs/qube.yaml --set negatives --pilot
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import licenses, stage  # noqa: E402

WAKEWORD_ROOT = Path(__file__).resolve().parent.parent
DATASETS_ROOT = WAKEWORD_ROOT / "datasets"

# Provenance applied to generated feature files (audio sources are all CC-BY-4.0).
_NEGATIVE_PROVENANCE = {
    "dataset": "LibriSpeech",
    "source_url": "https://www.openslr.org/12",
    "license_id": "CC-BY-4.0",
    "commercial_use": True,
    "attribution": "LibriSpeech ASR corpus, V. Panayotov et al. (2015). CC-BY-4.0.",
}
_VALIDATION_PROVENANCE = {
    "dataset": "LibriSpeech+MUSAN",
    "source_url": "https://www.openslr.org/12 ; https://www.openslr.org/17",
    "license_id": "CC-BY-4.0",
    "commercial_use": True,
    "attribution": (
        "LibriSpeech (Panayotov et al., 2015) + MUSAN (Snyder et al., 2015). CC-BY-4.0."
    ),
}

# Pilot caps keep a smoke run fast (M3 pilots / CI sanity).
_PILOT_NEGATIVE_ROWS = 5_000
_PILOT_VALIDATION_ROWS = 1_000


def _resolve(path_str: str) -> Path:
    path = Path(path_str)
    return path if path.is_absolute() else (WAKEWORD_ROOT / path)


def _resolve_sources(config: dict, key: str, override: list[str] | None) -> list[Path]:
    raw = override if override else config.get("data", {}).get(key, [])
    return [_resolve(str(p)) for p in raw]


def _build_set(
    *,
    label: str,
    sources: list[Path],
    output: Path,
    provenance: dict,
    max_rows: int | None,
) -> int:
    from lib import features  # lazy: pulls numpy/openwakeword

    existing = [p for p in sources if p.exists()]
    if not existing:
        print(
            f"ERROR [{label}]: no source audio found in "
            f"{', '.join(str(s) for s in sources)}. Run download_datasets.py first.",
            file=sys.stderr,
        )
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    file_iter = features.audio.iter_audio_files(existing)
    rows = features.compute_features(file_iter, output, max_rows=max_rows)

    licenses.write_manifest(output, datasets_root=DATASETS_ROOT, notes=f"Generated by precompute_features.py ({label}).", **provenance)
    print(f"OK [{label}]: wrote {rows} feature rows -> {output}")
    return rows


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    stage.add_config_arg(parser)
    parser.add_argument(
        "--set",
        choices=["negatives", "validation", "all"],
        default="all",
        help="Which feature set to compute.",
    )
    parser.add_argument("--pilot", action="store_true", help="Cap rows for a fast smoke run.")
    parser.add_argument("--max-rows", type=int, default=None, help="Explicit row cap (overrides --pilot).")
    parser.add_argument("--negative-sources", nargs="*", help="Override negative source audio dirs.")
    parser.add_argument("--validation-sources", nargs="*", help="Override validation source audio dirs.")
    args = parser.parse_args(argv)
    config = stage.load_stage_config(args)

    data = config.get("data", {})
    neg_out = _resolve(data.get("negative_features", "datasets/features/negatives.npy"))
    val_out = _resolve(data.get("fp_validation_features", "datasets/features/fp_validation.npy"))

    neg_cap = args.max_rows if args.max_rows is not None else (_PILOT_NEGATIVE_ROWS if args.pilot else None)
    val_cap = args.max_rows if args.max_rows is not None else (_PILOT_VALIDATION_ROWS if args.pilot else None)

    total = 0
    if args.set in ("negatives", "all"):
        total += _build_set(
            label="negatives",
            sources=_resolve_sources(config, "negative_source_paths", args.negative_sources),
            output=neg_out,
            provenance=_NEGATIVE_PROVENANCE,
            max_rows=neg_cap,
        )
    if args.set in ("validation", "all"):
        total += _build_set(
            label="validation",
            sources=_resolve_sources(config, "validation_source_paths", args.validation_sources),
            output=val_out,
            provenance=_VALIDATION_PROVENANCE,
            max_rows=val_cap,
        )

    if total == 0:
        print("No features were produced. See errors above.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
