#!/usr/bin/env python3
"""Deterministic prompt exporter for Starfall (the "baton" generator).

Renders the next-run prompt pack from the durable memory files — NO LLM, no
creativity, identical output every time — mirroring the verifier subsystem's
philosophy (`starfall_verify.py`). Given the same inputs it produces the same
prompts, so nothing is silently omitted between phases.

Inputs (read-only):
  * `.cursor/starfall/roadmap.md`       — phase table -> {phase, scope, work item, status}
  * `.cursor/starfall/handoff.md`       — STATUS + "Next slice" + "Constraints" blocks
  * `.cursor/starfall/known-issues.md`  — open KIs to carry forward
  * `.cursor/starfall/open-questions.md`— open questions and which phase they block
  * current git branch (best-effort)

Outputs (written under `.cursor/starfall/prompts/`):
  * `next.md`            — the immediate next run (handoff "Next slice" if present,
                           else the lowest not-complete phase)
  * `phase-<n>.md`       — one per not-complete roadmap phase
  * `phase-<n>-review.md`— reviewer counterpart (with --review / by default)

CLI:
  python .cursor/hooks/starfall_export.py            # regenerate the whole pack
  python .cursor/hooks/starfall_export.py --phase N  # print one phase prompt to stdout
  python .cursor/hooks/starfall_export.py --phase next
  python .cursor/hooks/starfall_export.py --no-review # skip reviewer prompts
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

HOOK_DIR = Path(__file__).resolve().parent
CURSOR_DIR = HOOK_DIR.parent
REPO = CURSOR_DIR.parent
MEM = CURSOR_DIR / "starfall"
PROMPTS = MEM / "prompts"

ROADMAP = MEM / "roadmap.md"
HANDOFF = MEM / "handoff.md"
ACTIVE_TASK = MEM / "active-task.md"
KNOWN_ISSUES = MEM / "known-issues.md"
OPEN_QUESTIONS = MEM / "open-questions.md"

GENERATED_BANNER = (
    "<!-- GENERATED by .cursor/hooks/starfall_export.py from roadmap.md + memory. "
    "Deterministic; do not hand-edit — re-run the exporter. -->"
)

_DEFAULT_CONSTRAINTS = (
    "- MCP is a provider only; no raw MCP tools exposed as primary UX (P1/P2).\n"
    "- No `import mcp` / `provider == \"mcp\"` outside `providers/mcp/` (P6).\n"
    "- Preserve P1-P8; every result carries `cap:` provenance (P4/P8).\n"
    "- Nothing defaults to write/destructive; unknown -> default-deny + review (P7)."
)

_WORKFLOW = (
    "Workflow: Discovery -> Architecture Review -> Implementation Plan -> "
    "Implementation Handoff -> Code -> Self-Review -> Testing -> Documentation -> Closing.\n"
    "Gates G1-G3 before Code; G4 before close. Never commit/push to main/master.\n"
    "Close only when G1-G4 PASS and handoff STATUS: READY (evidence-verified by "
    "starfall_verify)."
)


@dataclass
class Phase:
    num: int
    scope: str
    work_item: str
    status: str

    @property
    def complete(self) -> bool:
        return "COMPLETE" in self.status.upper()


def read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8") if path.exists() else ""
    except Exception:
        return ""


def git_branch() -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO), "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        b = out.stdout.strip()
        return b or "<feature-branch>"
    except Exception:
        return "<feature-branch>"


def parse_phases(text: str) -> list[Phase]:
    """Parse the roadmap markdown table rows into Phase records (header/sep skipped)."""
    phases: list[Phase] = []
    row = re.compile(r"^\s*\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*(#?\d+)\s*\|\s*(.+?)\s*\|\s*$")
    for line in text.splitlines():
        m = row.match(line)
        if not m:
            continue
        phases.append(Phase(int(m.group(1)), m.group(2), m.group(3), m.group(4)))
    return sorted(phases, key=lambda p: p.num)


def _block_between(text: str, start_kw: str, stop_kws: tuple[str, ...]) -> str:
    """Return text from the line containing start_kw up to the first stop keyword."""
    lines = text.splitlines()
    start = next((i for i, ln in enumerate(lines) if start_kw.lower() in ln.lower()), None)
    if start is None:
        return ""
    body = lines[start:]
    end = len(body)
    for i, ln in enumerate(body[1:], 1):
        if any(k.lower() in ln.lower() for k in stop_kws):
            end = i
            break
    return "\n".join(body[:end]).strip()


def handoff_status(text: str) -> str:
    for line in text.splitlines():
        m = re.match(r"\s*STATUS:\s*([A-Za-z]+)\s*$", line)
        if m:
            return m.group(1).upper()
    return ""


def next_slice_block(text: str) -> str:
    block = _block_between(
        text, "next slice",
        ("Constraints", "Test requirements", "Open questions"),
    )
    return block


def constraints_block(text: str) -> str:
    block = _block_between(text, "Constraints", ("Test requirements", "Open questions"))
    # Drop the heading line itself; keep the bullets.
    if block:
        lines = block.splitlines()
        return "\n".join(lines[1:]).strip() or _DEFAULT_CONSTRAINTS
    return _DEFAULT_CONSTRAINTS


def open_known_issues(text: str) -> list[str]:
    issues: list[str] = []
    for m in re.finditer(r"^##\s+(KI\d+[^\n]*?)\s*\[(open|mitigated)\]", text, re.MULTILINE):
        issues.append(m.group(1).strip())
    return issues


def blocking_questions(text: str) -> dict[int, list[str]]:
    """Map phase number -> [question ids] for open questions that block it."""
    result: dict[int, list[str]] = {}
    blocks = re.split(r"(?m)^##\s+", text)
    for b in blocks[1:]:
        header = b.splitlines()[0] if b.strip() else ""
        qid_m = re.match(r"(Q\d+)", header)
        if not qid_m or "[open]" not in header.lower():
            continue
        qid = qid_m.group(1)
        blk_line = next((ln for ln in b.splitlines() if ln.lower().startswith("blocking:")), "")
        for ph in re.findall(r"Phase\s+(\d+)", blk_line):
            result.setdefault(int(ph), []).append(qid)
    return result


# --------------------------------------------------------------------------- render

def _ki_section(kis: list[str]) -> str:
    if not kis:
        return "- none open"
    return "\n".join(f"- {k}" for k in kis)


def render_phase(phase: Phase, *, branch: str, constraints: str, kis: list[str],
                 blockers: dict[int, list[str]]) -> str:
    wi = phase.work_item if phase.work_item.startswith("#") else f"#{phase.work_item}"
    precondition = (
        f"Phase {phase.num - 1} complete (see roadmap.md)." if phase.num > 0
        else "Foundations phase."
    )
    blocking_note = ""
    if phase.num in blockers:
        qs = ", ".join(blockers[phase.num])
        blocking_note = (
            f"\nFIRST resolve open-question(s) {qs} in "
            "`.cursor/starfall/open-questions.md` — they block this phase.\n"
        )
    return (
        f"{GENERATED_BANNER}\n\n"
        f"starfall implement Phase {phase.num} ({wi}): {phase.scope}, on branch `{branch}`.\n\n"
        f"Precondition: {precondition}{blocking_note}\n"
        "Read `.cursor/starfall/handoff.md`, `.cursor/starfall/active-task.md`, and "
        "`.cursor/starfall/drift-rules.md` first; refresh `active-task.md` for this phase.\n\n"
        f"Objectives:\n{phase.scope}\n\n"
        f"Carried-forward known issues:\n{_ki_section(kis)}\n\n"
        f"Constraints (must hold):\n{constraints}\n\n"
        f"{_WORKFLOW}\n"
    )


def render_review(phase: Phase, *, branch: str) -> str:
    wi = phase.work_item if phase.work_item.startswith("#") else f"#{phase.work_item}"
    return (
        f"{GENERATED_BANNER}\n\n"
        f"Review the Phase {phase.num} ({wi}) implementation on branch `{branch}`. "
        "READ-ONLY — do not modify code; produce findings only.\n\n"
        "Verify:\n"
        "- Every P1-P8 principle holds against the actual diff (cite files).\n"
        "- `.cursor/starfall/drift-rules.md`: no FAIL condition is triggered.\n"
        "- `.cursor/starfall/test-plan.md` cases exist and pass.\n"
        "- The `handoff.md` \"Delivered\" files all exist and match the claims.\n"
        "- No P6 leak (no MCP import / provider branch outside `providers/mcp/`).\n\n"
        "Output: a findings list (PASS / CONCERN / BLOCKER per item) plus a go/no-go "
        "recommendation for merge. Do not edit files.\n"
    )


def render_next(*, handoff_text: str, branch: str, constraints: str, kis: list[str],
                first_incomplete: Phase | None,
                blockers: dict[int, list[str]]) -> str:
    """The immediate baton: handoff 'Next slice' if present, else first incomplete phase."""
    slice_block = next_slice_block(handoff_text)
    ready = handoff_status(handoff_text) == "READY"
    if ready and slice_block and len(slice_block.splitlines()) > 1:
        return (
            f"{GENERATED_BANNER}\n\n"
            "starfall implement the next slice defined in the approved handoff, on branch "
            f"`{branch}`.\n\n"
            "Source of truth: `.cursor/starfall/handoff.md` (below) + known-issues. Read "
            "`active-task.md`, `roadmap.md`, and `drift-rules.md` first.\n\n"
            f"--- handoff: {slice_block}\n\n"
            f"Carried-forward known issues:\n{_ki_section(kis)}\n\n"
            f"Constraints (must hold):\n{constraints}\n\n"
            f"{_WORKFLOW}\n"
        )
    if first_incomplete is not None:
        return render_phase(first_incomplete, branch=branch, constraints=constraints,
                            kis=kis, blockers=blockers)
    return (
        f"{GENERATED_BANNER}\n\n"
        "All roadmap phases are marked COMPLETE. Nothing to export — define the next "
        "initiative in `.cursor/starfall/active-task.md`.\n"
    )


# --------------------------------------------------------------------------- driver

def build_all(write: bool, include_review: bool) -> tuple[str, list[str]]:
    roadmap_text = read(ROADMAP)
    handoff_text = read(HANDOFF)
    branch = git_branch()
    phases = parse_phases(roadmap_text)
    constraints = constraints_block(handoff_text)
    kis = open_known_issues(read(KNOWN_ISSUES))
    blockers = blocking_questions(read(OPEN_QUESTIONS))
    incomplete = [p for p in phases if not p.complete]
    first_incomplete = incomplete[0] if incomplete else None

    written: list[str] = []
    if write:
        PROMPTS.mkdir(parents=True, exist_ok=True)

    def emit_file(name: str, content: str) -> None:
        if write:
            (PROMPTS / name).write_text(content, encoding="utf-8")
            written.append(name)

    emit_file("next.md", render_next(
        handoff_text=handoff_text, branch=branch, constraints=constraints, kis=kis,
        first_incomplete=first_incomplete, blockers=blockers))

    for p in incomplete:
        emit_file(f"phase-{p.num}.md", render_phase(
            p, branch=branch, constraints=constraints, kis=kis, blockers=blockers))
        if include_review:
            emit_file(f"phase-{p.num}-review.md", render_review(p, branch=branch))

    summary_lines = [
        f"Starfall exporter (branch: {branch})",
        "=" * 40,
        f"phases parsed:   {len(phases)} ({len(incomplete)} incomplete)",
        f"open KIs:        {len(kis)}",
        f"blocking Qs:     {blockers or 'none'}",
        f"handoff STATUS:  {handoff_status(handoff_text) or '<none>'}",
        f"files written:   {', '.join(written) if written else '(dry run)'}",
    ]
    return "\n".join(summary_lines), written


def print_one(selector: str, include_review: bool) -> int:
    roadmap_text = read(ROADMAP)
    handoff_text = read(HANDOFF)
    branch = git_branch()
    phases = parse_phases(roadmap_text)
    constraints = constraints_block(handoff_text)
    kis = open_known_issues(read(KNOWN_ISSUES))
    blockers = blocking_questions(read(OPEN_QUESTIONS))
    incomplete = [p for p in phases if not p.complete]
    first_incomplete = incomplete[0] if incomplete else None

    if selector == "next":
        print(render_next(handoff_text=handoff_text, branch=branch, constraints=constraints,
                          kis=kis, first_incomplete=first_incomplete, blockers=blockers))
        return 0
    try:
        n = int(selector)
    except ValueError:
        print(f"unknown --phase selector: {selector!r} (use 'next' or a phase number)",
              file=sys.stderr)
        return 2
    match = next((p for p in phases if p.num == n), None)
    if match is None:
        print(f"phase {n} not found in roadmap.md", file=sys.stderr)
        return 2
    print(render_review(match, branch=branch) if include_review
          else render_phase(match, branch=branch, constraints=constraints, kis=kis,
                            blockers=blockers))
    return 0


def main() -> None:
    ap = argparse.ArgumentParser(description="Deterministic Starfall prompt exporter.")
    ap.add_argument("--phase", help="'next' or a phase number: print one prompt to stdout")
    ap.add_argument("--review", action="store_true",
                    help="with --phase: print the reviewer prompt instead")
    ap.add_argument("--no-review", action="store_true",
                    help="regenerating the pack: skip reviewer prompts")
    args = ap.parse_args()

    if args.phase is not None:
        sys.exit(print_one(args.phase, include_review=args.review))

    summary, _ = build_all(write=True, include_review=not args.no_review)
    print(summary)


if __name__ == "__main__":
    main()
